#!/bin/sh
ps aux |grep server | grep -v grep
echo findap start time
cat findapst
echo findap progress 
date
grep findap /var/log/scan.log | grep 'scan file' | tail -1
grep findap /var/log/scan.log | grep scan |grep -v file  |tail -5

echo findap failed
date
grep findap /var/log/scan.log | grep failed | tail -5


echo findap git
date
grep findap /var/log/scan.log | grep bug | tail -5

echo findap git bug 
date
grep findap /var/log/scan.log | grep 'find git' | tail -5
echo 'total:'+`grep findap /var/log/scan.log | grep -c 'find git'`
