#!/bin/sh
#./syslog.etc
cd ../syn

#sip=`ifconfig | grep inet | grep -v 127.0.0.1 | awk {'print $2'} |sed -n '2p'| cut -d: -f2`
#echo $sip

#exec ./synscan -s 10.104.159.52 -f /scandata/ip/120.ipcut -p 80 -w 20 -n 1 -t 20


exec ./synscan -s 10.104.159.52 -f /scandata/ip/113.ipcut -p 80 -w 20 -n 1 -t 20
 
